### ISSUE TITLE
.well-known

### ISSUE THREAD

**Issue by josh** [web-services/services-json#1]
Hey @csuwildcat,

Have you considered using the `/.well-known/` prefix instead of having `services.json` live at the url root?

https://tools.ietf.org/html/rfc5785

**Comment by csuwildcat** [comment]
This is a good idea, let's look into what (if any) differences and downstream affects they each have. On first blush, I can't see anything wrong with using this.

**Comment by csuwildcat** [comment]
@josh I think we can make this work, I really want to defer to the group consensus, so whatever you think is right.

**Comment by josh** [comment]
Cool, just wanted to float the idea to you.
